services:
  web:
    image: my-django-app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app # This mounts your app directory to the container
      - ./db.sqlite3:/app/db.sqlite3 # Persist SQLite DB
    env_file: .env