services:
  web:
    image: my-django-app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # This will mount your app directory to the container
      - ./db.sqlite3:/app/db.sqlite3  # This ensures the SQLite DB is persisted
    env_file: .env