services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django-docker
    #image: sds-app
    volumes:
      - ./static:/app/staticfiles
      - ./db:/app/db # Map the root-level staticfiles folder
    
    env_file: .env.prod

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro   
    depends_on:
      - web
volumes:
  db: