services:
  web:
    image: my-django-app
    command: gunicorn SUN.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/staticfiles # Map the root-level staticfiles folder
    build:
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file: .env.prod

  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/staticfiles # Map the root-level staticfiles folder
    ports:
      - 1337:80
    depends_on:
      - web

volumes: {}