services:
  web:
    image: my-django-app
    command: gunicorn my-django-app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles # Fixed volume reference
    build:
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file: .env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles # Fixed volume reference
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: # Declare the named volume here
