# Generated by Django 5.1.3 on 2024-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_msds_cas_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='cas_number',
            field=models.IntegerField(verbose_name='CAS Number'),
        ),
    ]
