# Generated by Django 5.1.3 on 2024-11-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_msds_cas_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='index_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='product_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='reach_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
