# Generated by Django 5.1.3 on 2024-11-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_msds_index_number_alter_msds_product_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='cas_number',
            field=models.CharField(max_length=20, verbose_name='CAS Number'),
        ),
    ]
