# Generated by Django 5.1.3 on 2024-11-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_msds_cas_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='classification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='label_elements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
