# Generated by Django 5.1.3 on 2024-11-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_msds_classification_alter_msds_label_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='msds',
            name='signal_word',
            field=models.CharField(choices=[('warning', 'Warning'), ('danger', 'Danger')], default='warning', max_length=7),
        ),
    ]
