# Generated by Django 5.1.3 on 2024-11-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_msds_signal_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='signal_word',
            field=models.TextField(blank=True, null=True),
        ),
    ]
