# Generated by Django 5.1.3 on 2024-11-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_msds_signal_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='signal_word',
            field=models.CharField(choices=[('Warning', 'Warning'), ('Danger', 'Danger')], default='Warning', max_length=7),
        ),
    ]
