# Generated by Django 5.1.3 on 2024-11-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_msds_signal_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='msds',
            name='disposal_precautionary_statements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='general_precautionary_statements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='prevention_precautionary_statements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='response_precautionary_statements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='storage_precautionary_statements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='other_hazards',
            field=models.TextField(blank=True, null=True, verbose_name='Hazards not otherwise classified (HNOC)'),
        ),
    ]
