# Generated by Django 5.1.3 on 2024-11-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_msds_disposal_precautionary_statements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msds',
            old_name='ingredient_list',
            new_name='hazard_statements',
        ),
        migrations.RenameField(
            model_name='msds',
            old_name='ec_number',
            new_name='unique_identifiers',
        ),
    ]
