# Generated by Django 5.1.3 on 2024-11-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_ingredient_list_msds_hazard_statements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msds',
            old_name='unique_identifiers',
            new_name='other_unique_identifiers',
        ),
    ]
