# Generated by Django 5.1.3 on 2024-11-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_rename_unique_identifiers_msds_other_unique_identifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='cas_number',
            field=models.CharField(default='', max_length=20, verbose_name='CAS Number'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='index_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='reach_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
