# Generated by Django 5.1.3 on 2024-11-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_msds_cas_number_alter_msds_index_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msds',
            name='concentration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
