# Generated by Django 5.1.3 on 2024-11-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_msds_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='manufacturer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='recommended_use',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
