# Generated by Django 5.1.3 on 2024-11-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_msds_manufacturer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msds',
            name='description_of_first_aid',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='immediate_medical_attention',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='most_important_symptoms',
        ),
        migrations.AddField(
            model_name='msds',
            name='aid_eye',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='aid_inges',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='aid_inhal',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='aid_skin',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='symp_eye',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='symp_inges',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='symp_inhal',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='symp_skin',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
