# Generated by Django 5.1.3 on 2024-12-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_msds_aid_eye_alter_msds_aid_inges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msds',
            old_name='control_parameters',
            new_name='occupational_exposure_limits',
        ),
        migrations.AddField(
            model_name='msds',
            name='immediate_attention',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Indication of immediate medical attention and special treatment needed, if necessary.'),
        ),
    ]
