# Generated by Django 5.1.3 on 2024-12-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_rename_control_parameters_msds_occupational_exposure_limits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='appropriate_engineering_controls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='conditions_for_safe_storage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='emergency_procedures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='environmental_precautions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='individual_protection_measures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='methods_and_materials_for_containment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='occupational_exposure_limits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='personal_precautions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='precautions_for_safe_handling',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='protective_equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='special_protective_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='specific_hazards_arising',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='suitable_extinguishing_media',
            field=models.TextField(blank=True, null=True),
        ),
    ]
