# Generated by Django 5.1.3 on 2024-12-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_msds_appropriate_engineering_controls_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msds',
            old_name='occupational_exposure_limits',
            new_name='control_parameters',
        ),
    ]
