# Generated by Django 5.1.3 on 2024-12-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_rename_occupational_exposure_limits_msds_control_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msds',
            old_name='flammability',
            new_name='boiling_point',
        ),
        migrations.RenameField(
            model_name='msds',
            old_name='initial_boiling_point',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='msds',
            old_name='melting_point_freezing_point',
            new_name='flammability_information',
        ),
        migrations.RenameField(
            model_name='msds',
            old_name='odor_threshold',
            new_name='relative_vapour_density',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='partition_coefficient',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='relative_density',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='upper_lower_flammability_limits',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='vapor_density',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='viscosity',
        ),
        migrations.AddField(
            model_name='msds',
            name='density',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Density and/or relative density'),
        ),
        migrations.AddField(
            model_name='msds',
            name='kinematic_viscosity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='particle_characteristics',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='msds',
            name='partition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Partition coefficient: n-octanol/water (log value)'),
        ),
        migrations.AddField(
            model_name='msds',
            name='phys',
            field=models.CharField(default='', max_length=200, verbose_name='Physical State/Appearance'),
        ),
        migrations.AddField(
            model_name='msds',
            name='t_change',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Melting Point/Freezing Point'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='decomposition_temperature',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='msds',
            name='odor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
