# Generated by Django 5.1.3 on 2024-12-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_rename_flammability_msds_boiling_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='phys',
            field=models.TextField(verbose_name='Physical State/Appearance'),
        ),
    ]
