# Generated by Django 5.1.3 on 2024-12-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_msds_chemical_stability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msds',
            name='disposal_precautionary_statements',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='general_precautionary_statements',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='prevention_precautionary_statements',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='response_precautionary_statements',
        ),
        migrations.RemoveField(
            model_name='msds',
            name='storage_precautionary_statements',
        ),
        migrations.AddField(
            model_name='msds',
            name='disposal_statement_input',
            field=models.TextField(blank=True, null=True, verbose_name='Disposal Precautionary Statements'),
        ),
        migrations.AddField(
            model_name='msds',
            name='general_statement_input',
            field=models.TextField(blank=True, null=True, verbose_name='General Precautionary Statements'),
        ),
        migrations.AddField(
            model_name='msds',
            name='prevention_statement_input',
            field=models.TextField(blank=True, null=True, verbose_name='Prevention Precautionary Statements'),
        ),
        migrations.AddField(
            model_name='msds',
            name='response_statement_input',
            field=models.TextField(blank=True, null=True, verbose_name='Response Precautionary Statements'),
        ),
        migrations.AddField(
            model_name='msds',
            name='storage_statement_input',
            field=models.TextField(blank=True, null=True, verbose_name='Storage Precautionary Statements'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='pH',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='pH'),
        ),
    ]
