# Generated by Django 5.1.3 on 2024-12-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_msds_disposal_precautionary_statements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msds',
            old_name='disposal_statement_input',
            new_name='disposal_statements',
        ),
        migrations.RenameField(
            model_name='msds',
            old_name='general_statement_input',
            new_name='general_statements',
        ),
        migrations.RenameField(
            model_name='msds',
            old_name='prevention_statement_input',
            new_name='prevention_statements',
        ),
        migrations.RenameField(
            model_name='msds',
            old_name='response_statement_input',
            new_name='response_statements',
        ),
        migrations.RenameField(
            model_name='msds',
            old_name='storage_statement_input',
            new_name='storage_statements',
        ),
    ]
