# Generated by Django 5.1.3 on 2025-01-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_rename_disposal_statement_input_msds_disposal_statements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msds',
            name='information_on_toxicological_effects',
        ),
        migrations.AddField(
            model_name='msds',
            name='acute_toxicity_estimates',
            field=models.TextField(blank=True, help_text='Numerical measures of toxicity such as acute toxicity estimates.', null=True, verbose_name='Acute Toxicity Estimates'),
        ),
        migrations.AddField(
            model_name='msds',
            name='chronic_effects',
            field=models.TextField(blank=True, help_text='Information on chronic effects from short- and long-term exposure.', null=True, verbose_name='Chronic Effects'),
        ),
        migrations.AddField(
            model_name='msds',
            name='delayed_effects',
            field=models.TextField(blank=True, help_text='Information on delayed effects from exposure.', null=True, verbose_name='Delayed Effects'),
        ),
        migrations.AddField(
            model_name='msds',
            name='eye_contact_route',
            field=models.TextField(blank=True, help_text='Information on the likelihood of exposure via eye contact.', null=True, verbose_name='Eye Contact Route of Exposure'),
        ),
        migrations.AddField(
            model_name='msds',
            name='immediate_effects',
            field=models.TextField(blank=True, help_text='Information on immediate effects from exposure.', null=True, verbose_name='Immediate Effects'),
        ),
        migrations.AddField(
            model_name='msds',
            name='ingestion_route',
            field=models.TextField(blank=True, help_text='Information on the likelihood of exposure via ingestion.', null=True, verbose_name='Ingestion Route of Exposure'),
        ),
        migrations.AddField(
            model_name='msds',
            name='inhalation_route',
            field=models.TextField(blank=True, help_text='Information on the likelihood of exposure via inhalation.', null=True, verbose_name='Inhalation Route of Exposure'),
        ),
        migrations.AddField(
            model_name='msds',
            name='skin_contact_route',
            field=models.TextField(blank=True, help_text='Information on the likelihood of exposure via skin contact.', null=True, verbose_name='Skin Contact Route of Exposure'),
        ),
        migrations.AddField(
            model_name='msds',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Symptoms related to physical, chemical, and toxicological characteristics.', null=True, verbose_name='Symptoms Related to Characteristics'),
        ),
    ]
