# Generated by Django 5.1.3 on 2025-01-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_remove_msds_information_on_toxicological_effects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msds',
            name='UN_picto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
