# Generated by Django 5.1.3 on 2025-01-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_msds_un_picto'),
    ]

    operations = [
        migrations.AddField(
            model_name='msds',
            name='other_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
