# Generated by Django 5.1.3 on 2025-01-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_msds_other_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='msds',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
