# Generated by Django 5.1.3 on 2025-01-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_msds_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='other_hazards',
            field=models.TextField(blank=True, null=True, verbose_name='Hazards not otherwise classified (HNOC):'),
        ),
    ]
