# Generated by Django 5.1.3 on 2025-01-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_msds_other_hazards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
