# Generated by Django 5.1.3 on 2025-01-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_msds_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='UN_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número ONU'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='UN_picto',
            field=models.TextField(blank=True, null=True, verbose_name='Pictograma ONU'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='UN_proper_shipping_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de Envío Adecuado ONU'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='acute_toxicity_estimates',
            field=models.TextField(blank=True, help_text='Medidas numéricas de toxicidad, como estimaciones de toxicidad aguda.', null=True, verbose_name='Estimaciones de Toxicidad Aguda'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='aid_eye',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Medidas Necesarias para Contacto con los Ojos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='aid_inges',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Medidas Necesarias para Ingestión'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='aid_inhal',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Medidas Necesarias para Inhalación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='aid_skin',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Medidas Necesarias para Contacto con la Piel'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='appropriate_engineering_controls',
            field=models.TextField(blank=True, null=True, verbose_name='Controles de Ingeniería Apropiados'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='auto_ignition_temperature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Temperatura de Autoignición'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='bioaccumulative_potential',
            field=models.TextField(blank=True, null=True, verbose_name='Potencial de Bioacumulación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='boiling_point',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Punto de Ebullición'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='cas_number',
            field=models.CharField(default='', max_length=20, verbose_name='Número CAS'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='chemical_name',
            field=models.CharField(max_length=200, verbose_name='Nombre Químico'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='chemical_stability',
            field=models.TextField(blank=True, null=True, verbose_name='Estabilidad Química'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='chronic_effects',
            field=models.TextField(blank=True, help_text='Información sobre los efectos crónicos de la exposición a corto y largo plazo.', null=True, verbose_name='Efectos Crónicos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='classification',
            field=models.TextField(blank=True, null=True, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='colour',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='concentration',
            field=models.TextField(blank=True, null=True, verbose_name='Concentración'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='conditions_for_safe_storage',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones para un Almacenamiento Seguro'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='conditions_to_avoid',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones a Evitar'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='control_parameters',
            field=models.TextField(blank=True, null=True, verbose_name='Parámetros de Control'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='date_of_preparation',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Preparación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='decomposition_temperature',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Temperatura de Descomposición'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='delayed_effects',
            field=models.TextField(blank=True, help_text='Información sobre los efectos retardados de la exposición.', null=True, verbose_name='Efectos Retardados'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='density',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Densidad y/o Densidad Relativa'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='disclaimer',
            field=models.TextField(blank=True, null=True, verbose_name='Descargo de Responsabilidad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='disposal_methods',
            field=models.TextField(blank=True, null=True, verbose_name='Métodos de Eliminación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='disposal_statements',
            field=models.TextField(blank=True, null=True, verbose_name='Frases de Eliminación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='ecotoxicity',
            field=models.TextField(blank=True, null=True, verbose_name='Ecotoxicidad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de Emergencia'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='emergency_procedures',
            field=models.TextField(blank=True, null=True, verbose_name='Procedimientos de Emergencia'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='environmental_hazards',
            field=models.TextField(blank=True, null=True, verbose_name='Peligros Ambientales'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='environmental_precautions',
            field=models.TextField(blank=True, null=True, verbose_name='Precauciones Ambientales'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='evaporation_rate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tasa de Evaporación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='eye_contact_route',
            field=models.TextField(blank=True, help_text='Información sobre la probabilidad de exposición por contacto con los ojos.', null=True, verbose_name='Vía de Exposición: Contacto con los Ojos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='flammability_information',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Información de Inflamabilidad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='flash_point',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Punto de Inflamación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='general_statements',
            field=models.TextField(blank=True, null=True, verbose_name='Frases Precautorias Generales'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='hazard_statements',
            field=models.TextField(blank=True, null=True, verbose_name='Frases de Peligro'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='hazardous_decomposition_products',
            field=models.TextField(blank=True, null=True, verbose_name='Productos de Descomposición Peligrosos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='immediate_attention',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Indicaciones para Atención Médica Inmediata'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='immediate_effects',
            field=models.TextField(blank=True, help_text='Información sobre los efectos inmediatos de la exposición.', null=True, verbose_name='Efectos Inmediatos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='incompatible_materials',
            field=models.TextField(blank=True, null=True, verbose_name='Materiales Incompatibles'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='index_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Número de Índice'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='individual_protection_measures',
            field=models.TextField(blank=True, null=True, verbose_name='Medidas de Protección Individual'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='ingestion_route',
            field=models.TextField(blank=True, help_text='Información sobre la probabilidad de exposición por ingestión.', null=True, verbose_name='Vía de Exposición: Ingestión'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='inhalation_route',
            field=models.TextField(blank=True, help_text='Información sobre la probabilidad de exposición por inhalación.', null=True, verbose_name='Vía de Exposición: Inhalación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='kinematic_viscosity',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Viscosidad Cinématica'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='label_elements',
            field=models.JSONField(blank=True, null=True, verbose_name='Elementos de Etiqueta'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='last_revision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última Fecha de Revisión'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='manufacturer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección del Fabricante'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Fabricante'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='methods_and_materials_for_containment',
            field=models.TextField(blank=True, null=True, verbose_name='Métodos y Materiales para la Contención'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='mobility_in_soil',
            field=models.TextField(blank=True, null=True, verbose_name='Movilidad en el Suelo'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='odor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Olor'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='other_adverse_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Otros Efectos Adversos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='other_hazards',
            field=models.TextField(blank=True, null=True, verbose_name='Peligros no Clasificados de Otra Manera (HNOC)'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='other_information',
            field=models.TextField(blank=True, null=True, verbose_name='Otra Información'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='other_unique_identifiers',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otros Identificadores Únicos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='packing_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo de Embalaje'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='particle_characteristics',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Características de las Partículas'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='partition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Coeficiente de Reparto: n-octanol/agua (valor log)'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='persistence_and_degradability',
            field=models.TextField(blank=True, null=True, verbose_name='Persistencia y Degradabilidad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='personal_precautions',
            field=models.TextField(blank=True, null=True, verbose_name='Precauciones Personales'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='phys',
            field=models.TextField(verbose_name='Estado Físico/Apariencia'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='possibility_of_hazardous_reactions',
            field=models.TextField(blank=True, null=True, verbose_name='Posibilidad de Reacciones Peligrosas'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='precautions_for_safe_handling',
            field=models.TextField(blank=True, null=True, verbose_name='Precauciones para una Manipulación Segura'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='prevention_statements',
            field=models.TextField(blank=True, null=True, verbose_name='Frases de Prevención'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='product_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Producto'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='protective_equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Equipo de Protección'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='reach_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Número de Registro (REACH)'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='reactivity',
            field=models.TextField(blank=True, null=True, verbose_name='Reactividad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='recommended_use',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Uso Recomendado'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='relative_vapour_density',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Densidad Relativa del Vapor'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='response_statements',
            field=models.TextField(blank=True, null=True, verbose_name='Frases de Respuesta'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='restrictions_on_use',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Restricciones de Uso'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='safety_health_environmental_regulations',
            field=models.TextField(blank=True, null=True, verbose_name='Regulaciones de Seguridad, Salud y Medio Ambiente'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='signal_word',
            field=models.CharField(choices=[('Warning', 'Advertencia'), ('Danger', 'Peligro')], default='Warning', max_length=7, verbose_name='Palabra de Advertencia'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='skin_contact_route',
            field=models.TextField(blank=True, help_text='Información sobre la probabilidad de exposición por contacto con la piel.', null=True, verbose_name='Vía de Exposición: Contacto con la Piel'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='solubility',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Solubilidad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='special_precautions',
            field=models.TextField(blank=True, null=True, verbose_name='Precauciones Especiales'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='special_protective_actions',
            field=models.TextField(blank=True, null=True, verbose_name='Acciones de Protección Especial'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='specific_hazards_arising',
            field=models.TextField(blank=True, null=True, verbose_name='Peligros Específicos Derivados del Producto'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='storage_statements',
            field=models.TextField(blank=True, null=True, verbose_name='Frases de Almacenamiento'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='substance_or_mixture',
            field=models.CharField(blank=True, choices=[('substance', 'Sustancia'), ('mixture', 'Mezcla')], max_length=10, null=True, verbose_name='Sustancia o Mezcla'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='suitable_extinguishing_media',
            field=models.TextField(blank=True, null=True, verbose_name='Medios de Extinción Adecuados'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='symp_eye',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Síntomas Importantes para Contacto con los Ojos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='symp_inges',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Síntomas Importantes para Ingestión'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='symp_inhal',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Síntomas Importantes para Inhalación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='symp_skin',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Síntomas Importantes para Contacto con la Piel'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Síntomas relacionados con las características físicas, químicas y toxicológicas.', null=True, verbose_name='Síntomas Relacionados con las Características'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='synonyms',
            field=models.TextField(blank=True, null=True, verbose_name='Sinónimos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='t_change',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Punto de Fusión/Punto de Congelación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='transport_hazard_class',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clase de Peligro para el Transporte'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='transport_in_bulk',
            field=models.TextField(blank=True, null=True, verbose_name='Transporte a Granel'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='vapor_pressure',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Presión de Vapor'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión'),
        ),
    ]
