# Generated by Django 5.1.3 on 2025-05-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_msds_un_number_alter_msds_un_picto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_number', models.CharField(max_length=50, verbose_name='Número CAS')),
                ('chemical_name', models.CharField(max_length=200, verbose_name='Nombre de la sustancia')),
                ('molecular_formula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fórmula molecular')),
                ('boiling_point', models.CharField(blank=True, max_length=100, null=True, verbose_name='Punto de ebullición')),
                ('density', models.CharField(blank=True, max_length=100, null=True, verbose_name='Densidad y/o densidad relativa')),
                ('t_change', models.CharField(blank=True, max_length=100, null=True, verbose_name='Punto de fusión/congelación')),
                ('phys', models.TextField(blank=True, null=True, verbose_name='Estado físico/apariencia')),
                ('solubility', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solubilidad')),
                ('acute_toxicity_estimates', models.TextField(blank=True, null=True, verbose_name='Toxicidad aguda (estimada)')),
                ('chemtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='app1.chemtable', verbose_name='Cuadro de constantes')),
            ],
        ),
    ]
