# Generated by Django 5.1.3 on 2025-05-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_chemtable_chemical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='cas_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número CAS'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='chemical_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la sustancia'),
        ),
    ]
