# Generated by Django 5.1.3 on 2025-05-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_chemical_cas_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemtable',
            name='name',
        ),
    ]
