# Generated by Django 5.1.3 on 2025-05-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_remove_chemtable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='acute_toxicity_estimates',
            field=models.TextField(blank=True, help_text='Medidas numéricas de toxicidad, como estimaciones de toxicidad aguda.', max_length=1000, null=True, verbose_name='Estimaciones de Toxicidad Aguda'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='appropriate_engineering_controls',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Controles de Ingeniería Apropiados'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='bioaccumulative_potential',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Potencial de Bioacumulación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='chemical_stability',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Estabilidad Química'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='chronic_effects',
            field=models.TextField(blank=True, help_text='Información sobre los efectos crónicos de la exposición a corto y largo plazo.', max_length=1000, null=True, verbose_name='Efectos Crónicos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='conditions_for_safe_storage',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Condiciones para un Almacenamiento Seguro'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='conditions_to_avoid',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Condiciones a Evitar'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='control_parameters',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Parámetros de Control'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='delayed_effects',
            field=models.TextField(blank=True, help_text='Información sobre los efectos retardados de la exposición.', max_length=1000, null=True, verbose_name='Efectos Retardados'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='disclaimer',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descargo de Responsabilidad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='disposal_methods',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Métodos de Eliminación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='ecotoxicity',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ecotoxicidad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='emergency_procedures',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Procedimientos de Emergencia'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='environmental_hazards',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Peligros Ambientales'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='environmental_precautions',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Precauciones Ambientales'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='eye_contact_route',
            field=models.TextField(blank=True, help_text='Información sobre la probabilidad de exposición por contacto con los ojos.', max_length=1000, null=True, verbose_name='Vía de Exposición: Contacto con los Ojos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='hazardous_decomposition_products',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Productos de Descomposición Peligrosos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='immediate_effects',
            field=models.TextField(blank=True, help_text='Información sobre los efectos inmediatos de la exposición.', max_length=1000, null=True, verbose_name='Efectos Inmediatos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='incompatible_materials',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Materiales Incompatibles'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='individual_protection_measures',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Medidas de Protección Individual'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='ingestion_route',
            field=models.TextField(blank=True, help_text='Información sobre la probabilidad de exposición por ingestión.', max_length=1000, null=True, verbose_name='Vía de Exposición: Ingestión'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='inhalation_route',
            field=models.TextField(blank=True, help_text='Información sobre la probabilidad de exposición por inhalación.', max_length=1000, null=True, verbose_name='Vía de Exposición: Inhalación'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='methods_and_materials_for_containment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Métodos y Materiales para la Contención'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='mobility_in_soil',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Movilidad en el Suelo'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='other_adverse_effects',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Otros Efectos Adversos'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='other_information',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Otra Información'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='persistence_and_degradability',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Persistencia y Degradabilidad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='personal_precautions',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Precauciones Personales'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='phys',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Estado Físico/Apariencia'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='possibility_of_hazardous_reactions',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Posibilidad de Reacciones Peligrosas'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='precautions_for_safe_handling',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Precauciones para una Manipulación Segura'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='protective_equipment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Equipo de Protección'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='reactivity',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Reactividad'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='safety_health_environmental_regulations',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Regulaciones de Seguridad, Salud y Medio Ambiente'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='skin_contact_route',
            field=models.TextField(blank=True, help_text='Información sobre la probabilidad de exposición por contacto con la piel.', max_length=1000, null=True, verbose_name='Vía de Exposición: Contacto con la Piel'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='special_precautions',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Precauciones Especiales'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='special_protective_actions',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Acciones de Protección Especial'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='specific_hazards_arising',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Peligros Específicos Derivados del Producto'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='suitable_extinguishing_media',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Medios de Extinción Adecuados'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Síntomas relacionados con las características físicas, químicas y toxicológicas.', max_length=1000, null=True, verbose_name='Síntomas Relacionados con las Características'),
        ),
        migrations.AlterField(
            model_name='msds',
            name='transport_in_bulk',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Transporte a Granel'),
        ),
    ]
